stages:
  - build

variables:
  REGISTRY: hub.alterway.fr

before_script:
  - if [[ "$CI_BUILD_REF_NAME" != master ]]; then REGISTRY="$REGISTRY/$CI_BUILD_REF_NAME"; fi

build:
  stage: build
  script:
    - docker build --pull -t $REGISTRY/nginx:1.9-ldap 1.9-ldap/ > /dev/null
    - docker build --pull -t $REGISTRY/nginx:1.10-auth-request 1.10-auth-request/ > /dev/null
    - docker push $REGISTRY/nginx:1.9-ldap > /dev/null
    - docker push $REGISTRY/nginx:1.10-auth-request > /dev/null
  only:
    - preprod
    - master
